[package]
name = "entropylab-mnemonic-core"
version = "0.1.0"
edition = "2021"
publish = false
license = "MIT"
[lib]
crate-type = ["rlib"]
[dependencies]
entropylab-hex-core = { path = "../hex-core" }
bip39 = { version = "=2.2.2", default-features = false }
[profile.release]
panic = "abort"
opt-level = "s"
